name: Android CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.9'

      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.9

      - name: Commit Gradle Wrapper files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Generate Gradle wrapper files"
          branch: ${{ github.head_ref || github.ref_name }}
