name: Android CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.9'

      - name: Build Release APK
        run: gradle assembleRelease

      - name: Set short SHA
        id: set_sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Rename APK with commit hash
        run: |
          mv app/build/outputs/apk/release/app-release.apk \
             app/build/outputs/apk/release/RelationShit-release-${{ steps.set_sha.outputs.short_sha }}.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: relationshit-release-${{ steps.set_sha.outputs.short_sha }}
          path: app/build/outputs/apk/release/RelationShit-release-${{ steps.set_sha.outputs.short_sha }}.apk
